const MAX_SPHERE_SPEED = 4
const ROTATION_ADJUSTMENT = 1
const GRAVITY = 0.1
const INTERVAL_BETWEEN_SPHERES = 1000

export default {
  MAX_SPHERE_SPEED,
  ROTATION_ADJUSTMENT,
  GRAVITY,
  INTERVAL_BETWEEN_SPHERES
}
