const GRAVITY = 0.5
const INTERVAL_BETWEEN_SPHERES = 500
const PIXEL_CHECK = 5
const HUMAN_TIME = 10000
const NUMBER_CHANGED_BY_COMPUTER = 10
const MAXIMUM_SLIDE = 300
const SLIDE_DELTA = 0.7

export default {
  GRAVITY,
  INTERVAL_BETWEEN_SPHERES,
  PIXEL_CHECK,
  HUMAN_TIME,
  NUMBER_CHANGED_BY_COMPUTER,
  MAXIMUM_SLIDE,
  SLIDE_DELTA
}
