const GRAVITY = 0.3
const INTERVAL_BETWEEN_SPHERES = 2000
const PIXEL_CHECK = 5
const HUMAN_TIME = 5000
const NUMBER_CHANGED_BY_COMPUTER = 3
const NUMBER_CHANGED_BY_HUMAN = 3
const MAXIMUM_SLIDE = 50
const SLIDE_DELTA = 0.1

export default {
  GRAVITY,
  INTERVAL_BETWEEN_SPHERES,
  PIXEL_CHECK,
  HUMAN_TIME,
  NUMBER_CHANGED_BY_COMPUTER,
  MAXIMUM_SLIDE,
  SLIDE_DELTA,
  NUMBER_CHANGED_BY_HUMAN
}
